#!/bin/bash

#SBATCH --job-name=normal_diffusion_mode               # Name of the job
#SBATCH --output=job_output/normal_diff/%j.out         # Output file (%j is the job ID)
#SBATCH --cpus-per-task=1                              # Number of CPU cores requested
#SBATCH --gpus=h100:1                                  # Request 1 NVIDIA A100 GPU
#SBATCH --time=00-23:00:00                             # Maximum runtime (12 hours)
#SBATCH --mem=32G                                      # Amount of memory requested

echo "==== Job info ===="
echo "Running on: $(hostname)"
echo "Job ID: $SLURM_JOB_ID"
echo "Allocated GPUs:"
nvidia-smi
echo "--------------------"

source activate sd

echo "==== Python version and packages ===="
which python
python --version
python -c "import torch; print('Torch version:', torch.__version__)"

echo "==== Starting training script ===="

cd DiffuseStyleGestureReproduced

python run_training_normal_diff.py                                  # Run the Python script