_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 1
dataset_type:
    value: DataLoader
epochs:
    value: 10000
learning_rate:
    value: 0.0009913249959028253
num_of_decoder_layers:
    value: 2
num_of_encoder_layers:
    value: 2
optimizer:
    value: AdamW
pose_dim:
    value: 345
z_dim:
    value: 48
