#!/bin/bash
#SBATCH --partition scavenge
#SBATCH --nodes 1
#SBATCH --gpus=v100:1
#SBATCH --ntasks-per-node 1
#SBATCH --time 03:00:00
#SBATCH --job-name j_sliding_diffusion_jupyter_nb
#SBATCH --output notebook_output_files/jupyter-notebook-%J.log

# get tunneling info
XDG_RUNTIME_DIR=""
port=$(shuf -i8000-9999 -n1)
node=$(hostname -s)
user=$(pefu)
cluster=$(hostname -f | awk -F"." '{print $2}')

# print tunneling instructions jupyter-log
echo -e "
MacOS or linux terminal command to create your ssh tunnel
ssh -N -L ${port}:${node}:${port} ${user}@hpc.itu.dk

Windows MobaXterm info
Forwarded port: ${port}
Remote server: ${node}
Remote port: ${port}
SSH server: hpc.itu.dk
SSH login: $user
SSH port: 22

Use a Browser on your local machine to go to:
localhost:${port}  (prefix w/ https:// if using password)
"

# load Jupyter-Server module here along with an additional modules required
source activate sd
module load JupyterLab/3.5.0-GCCcore-11.3.0 

# Start the server
jupyter-notebook --no-browser --port=${port} --ip=0.0.0.0